version: "3"
services:
  server:
    image: gocd/gocd-server:v20.1.0
    ports:
      - "8153:8153"
      - "8154:8154"
  agent:
    build: go-agent/
    image: gocd-custom-agent:v20.1.0
    depends_on:
      - server
    environment:
      GO_SERVER_URL: "https://server:8154/go"